project-includes = [
    "backend",
    "tests",
]

project-excludes = [
    ".venv",
    ".venv-rvc",
    ".tmp",
    "dist",
    "models",
    "node_modules",
    "src-tauri/target",
]

search-path = [
    ".",
]

python-interpreter-path = ".venv/Scripts/python.exe"
